---
- name: Development stack
  hosts: localhost
  sudo: yes
  sudo_user: root
  #sudo_ask_pass: True

  vars:

    user: changeme
    user_path: "/home/{{ user }}"
    dotfiles_path: "{{ user_path }}/dotfiles"
    bashrc: "{{ user_path }}/.bashrc"
    zshrc: "{{ user_path }}/.zshrc"
    with_fonts: true
    cpu_arch: x86_64
    vagrant_version: 1.6.5

    # @todo extract bitbucket to role
    with_bitbucket: false
    bitbucket_user: ''
    bitbucket_password: ''

  #vars_prompt:

  #  bitbucket_user: "bitbucket user (empty for none)"
  #  bitbucket_password: "bitbucket password (empty ffor none)"

  roles:

    - { role: geerlingguy.php-xdebug }
    #- { role: geerlingguy.packer-debian }
    - { role: kosssi.composer }

  tasks:

    #
    # Repos
    #

    #- name: Ubuntu multiverse repo
    #  apt_repository: repo="{{item}}" update_cache="no"
    #  with_items:
    #    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    #    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    #    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    #    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    #  notify: update apt cache

    #- name: Node.js | Add the node.js PPA
    #  apt_repository: repo=ppa:chris-lea/node.js
    #  tags: nodejs

    #
    # Tools
    #

    - name: Tools
      apt: name="{{item}}" update_cache="yes"
      with_items:
        - build-essential
        - curl
        - htop
        - tmux
        - git
        - zsh
        - vim
        - exuberant-ctags
        - python
        - python-pip
        - python-dev
        - ruby
        - ruby-dev
        - virtualbox-guest-utils
        - virtualbox-guest-dkms
        - virtualbox
        - vagrant
        - php5
        - php5-intl
        - nodejs
        - npm
        # GUI
        #- mysql-workbench

    - name: Timestamp for backup file naming
      shell: date '+%Y_%m_%d_%H%M'
      register: timestamp
      tags: [ backup ]

    - name: dotfiles folder
      file: path="{{ dotfiles_path }}" state="directory"
    
    - name: dotfiles bin folder
      file: path="{{ dotfiles_path }}/bin" state="directory"


    - name: Installing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)
      git: >
        repo=https://github.com/robbyrussell/oh-my-zsh
        dest={{ dotfiles_path }}/.oh-my-zsh
      notify:
        - backup zshrc
        - create zshrc

    - name: default shell
      user: shell=/bin/zsh user={{ user }}
      when: user != "root"

    - name: Solarize term
      git: >
        repo=https://github.com/sigurdga/gnome-terminal-colors-solarized.git
        dest={{ dotfiles_path }}/solarized

    - name: Get fonts
      git: >
        repo=https://github.com/Lokaltog/powerline-fonts.git
        dest={{ dotfiles_path }}/.fonts
      register: fonts_clone
      when: with_fonts

    - name: Install fonts
      shell: fc-cache -vf {{ dotfiles_path }}/.fonts/*/*.ttf
      when: with_fonts and fonts_clone.changed

    - name: create zshrc
      shell: cp {{ dotfiles_path }}/.oh-my-zsh/templates/zshrc.zsh-template {{ zshrc }}

    - name: oh-my-zsh theme
      lineinfile: dest={{ zshrc }} line='ZSH_THEME=agnoster'

    - name: oh-my-zsh default user
      lineinfile: dest={{ zshrc }} line='DEFAULT_USER={{ user }}'

    - name: Install z
      git: >
        repo=https://github.com/rupa/z.git
        dest={{ dotfiles_path }}/z

    - name: Load z
      lineinfile: dest={{ zshrc }} line='. {{ dotfiles_path }}/z/z.sh'

    - name: FZF clone
      git: >
        repo=https://github.com/junegunn/fzf.git
        dest={{ user_path }}/.fzf
    # needs to be placed on ~/.fzf
      tags: [ fuzzy ]

    - name: FZF install
      shell: yes | {{ user_path }}/.fzf/install
      tags: [ fuzzy ]

    - name: shell - profile template
      template: src="templates/.profile" dest="{{ dotfiles_path }}/.profile"

    - name: shell - profile load for zsh
      lineinfile: dest={{ zshrc }} line='. {{ dotfiles_path }}/.profile'

    - name: custom bashrc
      copy: src=files/.bashrc dest={{ user_path }}/.bashrc

    - name: shell - profile load for bash
      lineinfile: dest={{ bashrc }} line='. {{ dotfiles_path }}/.profile'

    - name: ansible shell
      pip: name=ansible-shell
      tags: [ ansible ]
    #
    # Bitucket
    #

    - name: bitbucket cli
      pip: name="bitbucket-cli"
      when: with_bitbucket

    - name: bitbucket credentials template
      template: src="templates/.bitbucket" dest="{{ user_path }}/.bitbucket"
      when: with_bitbucket

    #
    # vagrant manual install
    #

    #- name: download vagrant
    #  get_url: url="https://dl.bintray.com/mitchellh/vagrant/vagrant_{{ vagrant_version }}_{{ cpu_arch }}.deb" dest="/tmp/vagrant_{{ vagrant_version }}_{{ cpu_arch }}.deb"

    #- name: install vagrant
    #  shell: dpkg -i /tmp/vagrant_{{ vagrant_version }}_{{ cpu_arch }}.deb

    #- name: remove vagrant installer
    #  shell: rm -f /tmp/vagrant_{{ vagrant_version }}_{{ cpu_arch }}.deb

    # obsolete plugin, use global-status instead
    #- name: plugin - vagrant list
    #  shell: vagrant plugin install vagrant-list

    #
    # Vim
    #

    # http://blog.joncairns.com/2012/05/using-vim-as-a-php-ide/

    - name: Check if spf13 is installed
      stat: path="{{ dotfiles_path }}/.spf13-vim-3/"
      register: spf_dir

    - name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
      shell: curl http://j.mp/spf13-vim3 -L -o - | sh
      when: spf_dir.stat.isdir is not defined

    - name: custom vimrc
      copy: src=files/.vimrc.local dest={{ user_path }}/.vimrc.local

    - name: custom vim bundles
      copy: src=files/.vimrc.bundles.local dest={{ user_path }}/.vimrc.bundles.local
      notify: install vim plugins

    - name: vim php refactor
      get_url: url="https://github.com/QafooLabs/php-refactoring-browser/releases/download/v0.0.4/refactor.phar" dest="{{ dotfiles_path }}/bin/refactor"

    - name: vim php refactor executable
      file: path="{{ dotfiles_path }}/bin/refactor" mode=0775

    #
    # Node & NPM
    #

    - name: node link for nodejs exec (solves grunt error)
      file: state=link src=/usr/bin/nodejs dest=/usr/bin/node
      tags: [ npm ]

    - name: npm global packages
      npm: global=yes name={{ item }}
      with_items:
        - grunt-cli
        - bower
      tags: [ npm ]


  handlers:

    - name: update apt cache
      apt: update_cache="yes"

    - name: backup zshrc
      shell: if [ -f {{ zshrc }} ]; then mv {{ zshrc }} {{ zshrc }}.backup.{{ timestamp }}; fi

    - name: create zshrc
      shell: cp {{ dotfiles_path }}/.oh-my-zsh/templates/zshrc.zsh-template {{ zshrc }}

    - name: install vim plugins
      shell: vim +BundleInstall +qall
